-- Run this in your Supabase SQL editor

-- Create subjects table with proper primary key
create table public.subjects (
  id bigint generated by default as identity primary key,
  subject_name text not null,
  description text,
  progress integer default 0,
  completion integer default 0,
  next_topic text,
  est_time text,
  level text default 'Beginner',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable row level security (RLS)
alter table public.subjects enable row level security;

-- Create policies for secure access
-- Allow anyone to read subjects
create policy "Allow public read access"
  on public.subjects
  for select
  using (true);

-- Allow only authenticated users with role='admin' to insert/update/delete
create policy "Allow admin write access"
  on public.subjects
  for all
  using (auth.jwt() ->> 'role' = 'admin');

-- Example: Insert some sample subjects
insert into public.subjects (subject_name, description, level, next_topic, est_time)
values 
  ('C Programming', 'Introduction to C programming language', 'Beginner', 'Pointers', '2 weeks'),
  ('Data Structures', 'Fundamental data structures and algorithms', 'Intermediate', 'Trees', '3 weeks'),
  ('Database Management', 'SQL and database design principles', 'Beginner', 'Joins', '4 weeks');